Update resume.md
resume.md
9:18-9:23    warning Unexpected emphasis marker `*`, expected `_`                      emphasis-marker remark-lint
  [cause]:
    3:1-3:79 info    Emphasis marker style `'_'` first defined for `'consistent'` here emphasis-marker remark-lint
⚠ 1 warning
Error: Process completed with exit code 1.